name: serafort_flutter
description: Enterprise IAM, secure token storage, and wildcard RBAC for Flutter cross-platform applications.
version: 0.1.0
publish_to: 'none'

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: '>=3.10.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.0
  crypto: ^3.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  test: ^1.24.0
